version: '3.3'

services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=sequelize
      # - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=elpepe
      - MYSQL_PORT=3307
    ports:
      - 3307:3306
    volumes:
    - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=elpepe
      - PMA_HOST=mysql
    ports:
      - 8080:80